Repository jjwm10625/Roomfit, pull requests merged in 2024-12, with the labels that each got.

#14 [FEATURE] 로그인 정보 수집 페이지 구현
  app/src/main/java/com/example/roomfit/presentation/MainActivity.kt
  app/src/main/java/com/example/roomfit/presentation/login/SignUpScreen.kt
  app/src/main/java/com/example/roomfit/presentation/login/UserInfoScreen.kt
  app/src/main/java/com/example/roomfit/ui/theme/Type.kt
  app/src/main/res/drawable/daynight.png
  app/src/main/res/drawable/daynight2.png
  app/src/main/res/drawable/dropdown.png
  app/src/main/res/drawable/school_search.png
  app/src/main/res/drawable/smoker.png
  app/src/main/res/drawable/smoker2.png
Labels: 영서🦊, ⚙️Feature

#16 [FEATURE] 마이페이지 구현
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/roomfit/presentation/MainActivity.kt
  app/src/main/java/com/example/roomfit/presentation/UserEditScreen.kt
  app/src/main/java/com/example/roomfit/presentation/UserScreen.kt
  app/src/main/java/com/example/roomfit/presentation/mate/UserCard.kt
  app/src/main/java/com/example/roomfit/ui/theme/Type.kt
  app/src/main/res/drawable/camera.png
  app/src/main/res/drawable/female.png
  app/src/main/res/drawable/male.png
  app/src/main/res/drawable/user_profile.png
Labels: 영서🦊, ⚙️Feature

#29 [Feat] 채팅 스크린 구현
  .idea/misc.xml
  app/src/main/java/com/example/roomfit/ChatViewModel.kt
  app/src/main/java/com/example/roomfit/presentation/ChatScreen.kt
  app/src/main/java/com/example/roomfit/presentation/MainActivity.kt
  app/src/main/java/com/example/roomfit/presentation/MessageScreen.kt
  app/src/main/java/com/example/roomfit/presentation/components/ChatRow.kt
  app/src/main/java/com/example/roomfit/ui/theme/Color.kt
  app/src/main/java/com/example/roomfit/ui/theme/Type.kt
  app/src/main/res/drawable/send.png
Labels: 영서🦊, ⚙️Feature

#34 [FEAT] 대학 목록 추가 및 검색 기능 구현
  app/src/main/java/com/example/roomfit/presentation/MainActivity.kt
  app/src/main/java/com/example/roomfit/presentation/UserEditScreen.kt
  app/src/main/java/com/example/roomfit/presentation/UserScreen.kt
  app/src/main/java/com/example/roomfit/presentation/components/LoginButton.kt
  app/src/main/java/com/example/roomfit/presentation/components/UserCard.kt
  app/src/main/java/com/example/roomfit/presentation/login/LoginScreen.kt
  app/src/main/java/com/example/roomfit/presentation/login/SignUpScreen.kt
  app/src/main/java/com/example/roomfit/presentation/login/UserInfoScreen.kt
  app/src/main/java/com/example/roomfit/util/PreferencesManager.kt
Labels: 영서🦊, 📌API, ⚙️Feature

#46 [FEAT] 내 찜 목록 연결
  app/src/main/java/com/example/roomfit/ScrapViewModel.kt
  app/src/main/java/com/example/roomfit/presentation/MainActivity.kt
  app/src/main/java/com/example/roomfit/presentation/ScrapScreen.kt
  app/src/main/java/com/example/roomfit/presentation/components/DetailMateCard.kt
  app/src/main/java/com/example/roomfit/presentation/components/DetailMateCard2.kt
  app/src/main/java/com/example/roomfit/presentation/components/DetailMateCard4.kt
  app/src/main/java/com/example/roomfit/presentation/components/DetailMateCard5.kt
  app/src/main/java/com/example/roomfit/presentation/components/ScrapMateCard.kt
  app/src/main/java/com/example/roomfit/presentation/detail/DetailScreen.kt
  app/src/main/java/com/example/roomfit/presentation/detail/DetailScreen2.kt
  app/src/main/java/com/example/roomfit/presentation/detail/DetailScreen4.kt
  app/src/main/java/com/example/roomfit/presentation/detail/DetailScreen5.kt
Labels: ⚙️Feature, 🔨Refactor, 채현☕

#37 [FEAT] 구글맵 api 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/roomfit/presentation/GoogleMapScreen.kt
  app/src/main/java/com/example/roomfit/presentation/MainActivity.kt
  app/src/main/java/com/example/roomfit/presentation/MyPostScreen.kt
  app/src/main/java/com/example/roomfit/presentation/WriteScreen.kt
  app/src/main/java/com/example/roomfit/presentation/components/MyPostCard.kt
  app/src/main/java/com/example/roomfit/presentation/components/WriteCard.kt
  app/src/main/java/com/example/roomfit/presentation/mate/NewPost.kt
  app/src/main/java/com/example/roomfit/presentation/mate/PostText.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 📌API, ⚙️Feature, 채현☕
